name: Deployment

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (SemVer: https://semver.org)'
        required: true
jobs:
  deploy:
    name: "NuGet Deployment"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout Repository
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Update version
      run: "sed -i \"s#<Version>0.0.0</Version>#<Version>${{ github.event.inputs.version }}</Version>#\" AniSharp/AniSharp.csproj"  
    - name: Build
      run: dotnet build AniSharp/AniSharp.csproj --configuration Release --no-restore
    - name: Push to NuGet
      run: dotnet nuget push AniSharp/bin/Release/*.nupkg
             --api-key ${{ secrets.NUGET_DEPLOY_KEY }}
             --source https://api.nuget.org/v3/index.json
    - name: Push to Github
      run: dotnet nuget push AniSharp/bin/Release/*.nupkg
             --api-key ${{ secrets.GITHUB_DEPLOY_KEY }}
             --source https://nuget.pkg.github.com/01-Feli/index.json
             --skip-duplicate
